Repository rit-construct-makerspace/makerspace, pull requests merged in 2022-01, with the labels that each got.

#36 Add call to our GraphQL API
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/pages/admin/training_modules/TrainingModulesPage.tsx
  client/src/pages/maker/create_reservation/AvailabilityStrip.tsx
Labels: enhancement

#50 Extract route definitions to separate component
  client/src/App.tsx
  client/src/Routes.tsx
Labels: enhancement, frontend

#56 prototype user management page
  client/src/Routes.tsx
  client/src/pages/admin/users/UserCard.tsx
  client/src/pages/admin/users/UsersPage.tsx
  client/src/test_data/Users.ts
  client/src/types/User.ts
Labels: enhancement, frontend

#62 First try at a correct schema no laughing
  server/src/schemas/usersSchema.ts
Labels: enhancement, backend

#69 Move equipment page components to their own folder
  client/src/Routes.tsx
  client/src/pages/both/equipment/EquipmentPage.tsx
  client/src/pages/both/equipment/MachineCard.tsx
Labels: refactoring, frontend

#70 Set default React port to 3001
  client/package.json
Labels: refactoring, frontend

#66 Audit logs Prototype Page
  client/src/App.tsx
  client/src/common/AuditLogRow.tsx
  client/src/pages/admin/audit_logs/AuditLogsPage.tsx
  client/src/test_data/Logs.ts
  client/src/types/Log.ts
Labels: enhancement, frontend

#67 Start prototype for specific user management page
  client/src/App.tsx
  client/src/Routes.tsx
  client/src/common/CurrentUserProvider.tsx
  client/src/pages/admin/manage_user/DangerZone.tsx
  client/src/pages/admin/manage_user/ManageUserPage.tsx
  client/src/pages/admin/manage_user/PrivilegeControl.tsx
  client/src/pages/admin/users/UserCard.tsx
Labels: enhancement, frontend
