Repository rit-construct-makerspace/makerspace, pull requests merged in 2022-03, with the labels that each got.

#140 Fullstack training modules
  client/src/Routes.tsx
  client/src/hooks/useTimedState.ts
  client/src/pages/admin/edit_module/EditModulePage.tsx
  client/src/pages/admin/edit_module/SaveStatus.tsx
  client/src/pages/admin/edit_module/quiz/ImageEmbedDraft.tsx
  client/src/pages/admin/edit_module/quiz/ModuleItemDraft.tsx
  client/src/pages/admin/edit_module/quiz/QuestionDraft.tsx
  client/src/pages/admin/edit_module/quiz/QuestionOptionDraft.tsx
  client/src/pages/admin/edit_module/quiz/QuizBuilder.tsx
  client/src/pages/admin/edit_module/quiz/TextDraft.tsx
  client/src/pages/admin/edit_module/quiz/YouTubeEmbedDraft.tsx
  client/src/pages/admin/training_modules/TrainingModule.tsx
  client/src/pages/admin/training_modules/TrainingModulesPage.tsx
  client/src/pages/maker/create_reservation/TimeLabelStrip.tsx
  client/src/queries/getModule.ts
  client/src/queries/getModules.ts
  client/src/types/Module.ts
  client/src/types/Quiz.ts
  server/package-lock.json
  server/src/db/migrations/20211010154323_build-training-tables.ts
  server/src/mappers/equipment/Equipment.ts
  server/src/mappers/training/moduleMapper.ts
  server/src/models/training/module.ts
  server/src/repositories/Training/ModuleRepository.ts
  server/src/repositories/Training/questionRepo.ts
  server/src/resolvers/trainingResolver.ts
  server/src/schemas/trainingSchema.ts
  server/src/test/service.test.ts
Labels: enhancement, refactoring, backend, frontend

#152 Storefront backend cleanup
  server/src/mappers/store/InventoryItemMapper.ts
  server/src/models/store/inventoryItem.ts
  server/src/models/store/inventoryItemInput.ts
  server/src/models/store/person.ts
  server/src/repositories/Store/inventoryRepository.ts
  server/src/repositories/Store/labelRepository.ts
  server/src/resolvers/storeFrontResolver.ts
  server/src/schemas/storeFrontSchema.ts
  server/src/test/inventoryRepo.test.ts
Labels: refactoring, backend

#153 Update inventory counts upon checkout
  client/package-lock.json
  client/src/pages/admin/storefront/StorefrontPage.tsx
Labels: enhancement, frontend

#154 Connect equipment management UI to backend
  client/src/Routes.tsx
  client/src/pages/admin/edit_equipment/EditEquipmentPage.tsx
  client/src/pages/admin/manage_equipment/AttachedModule.tsx
  client/src/pages/admin/manage_equipment/DeleteEquipmentButton.tsx
  client/src/pages/admin/manage_equipment/EquipmentEditor.tsx
  client/src/pages/admin/manage_equipment/ExistingEquipment.tsx
  client/src/pages/admin/manage_equipment/ManageEquipmentPage.tsx
  client/src/pages/admin/manage_equipment/NewEquipment.tsx
  client/src/pages/admin/monitor/RoomCard.tsx
  client/src/pages/admin/monitor/SelectRoomPage.tsx
  client/src/pages/admin/training_modules/TrainingModulesPage.tsx
  client/src/pages/both/equipment/EquipmentCard.tsx
  client/src/pages/both/equipment/EquipmentPage.tsx
  client/src/queries/getEquipments.ts
  client/src/queries/getRooms.ts
  client/src/types/Room.ts
  server/src/db/migrations/20211102194503_machines_table.ts
  server/src/db/migrations/20220305184048_room-fk-equipment.ts
  server/src/mappers/rooms/roomMapper.ts
  server/src/repositories/Equipment/EquipmentRepository.ts
  server/src/resolvers/equipmentResolver.ts
  server/src/resolvers/roomsResolver.ts
  server/src/schema.ts
  server/src/schemas/equipmentSchema.ts
  server/src/schemas/roomsSchema.ts
Labels: enhancement, frontend

#157 implement createStudentUser mutation
  server/src/db/migrations/20210923214317_initial_users.ts
  server/src/db/migrations/20220305183523_room-fk-users.ts
  server/src/mappers/users/userMapper.ts
  server/src/models/users/hold.ts
  server/src/models/users/privilege.ts
  server/src/models/users/user.ts
  server/src/repositories/Users/UserRepository.ts
  server/src/resolvers/roomsResolver.ts
  server/src/resolvers/usersResolver.ts
  server/src/schema.ts
  server/src/schemas/holdsSchema.ts
  server/src/schemas/usersSchema.ts
Labels: enhancement, backend

#158 implement privilege mutation
  server/src/repositories/Users/UserRepository.ts
  server/src/resolvers/usersResolver.ts
  server/src/schemas/usersSchema.ts
Labels: enhancement, backend

#160 Store hashed university ID in Users table
  server/src/db/migrations/20220310180432_university-id.ts
  server/src/mappers/users/userMapper.ts
  server/src/repositories/Users/UserRepository.ts
  server/src/resolvers/usersResolver.ts
  server/src/schemas/usersSchema.ts
Labels: enhancement, backend

#162 Manage users frontend
  client/src/Routes.tsx
  client/src/common/PrettyModal.tsx
  client/src/common/RequestWrapper2.tsx
  client/src/pages/admin/manage_user/DangerZone.tsx
  client/src/pages/admin/manage_user/ManageUserPage.tsx
  client/src/pages/admin/manage_user/PrivilegeControl.tsx
  client/src/pages/admin/users/InfoBlob.tsx
  client/src/pages/admin/users/PrivilegeChip.tsx
  client/src/pages/admin/users/PrivilegeControl.tsx
  client/src/pages/admin/users/UserCard.tsx
  client/src/pages/admin/users/UserModal.tsx
  client/src/pages/admin/users/UsersPage.tsx
  client/src/queries/getUsers.ts
  client/src/types/Privilege.ts
Labels: enhancement, frontend

#165 add login sequence diagram
  docs/login.puml
Labels: documentation

#166 obscure saml clock skew fix
  server/src/auth.ts
Labels: bug, backend

#168 Integrate w/ samltest.id & create DB entry for first timers
  client/package.json
  client/src/App.tsx
  client/src/common/CurrentUserProvider.tsx
  client/src/left_nav/LeftNav.tsx
  client/src/pages/admin/users/PrivilegeControl.tsx
  server/src/auth.ts
  server/src/db/migrations/20220316203223_first-time-users.ts
  server/src/mappers/users/userMapper.ts
  server/src/repositories/Users/UserRepository.ts
  server/src/resolvers/usersResolver.ts
  server/src/schemas/usersSchema.ts
  server/src/server.ts
Labels: enhancement, refactoring, backend, frontend

#170 Signup form fiesta
  client/package-lock.json
  client/src/Routes.tsx
  client/src/common/CurrentUserProvider.tsx
  client/src/left_nav/LeftNav.tsx
  client/src/pages/admin/users/PrivilegeControl.tsx
  client/src/pages/admin/users/UserModal.tsx
  client/src/pages/maker/signup/SignupPage.tsx
  client/src/queries/getUsers.ts
  server/src/db/migrations/20220316203223_first-time-users.ts
  server/src/mappers/users/userMapper.ts
  server/src/repositories/Users/UserRepository.ts
  server/src/resolvers/usersResolver.ts
  server/src/schemas/usersSchema.ts
Labels: enhancement, backend, frontend

#175 Audit log enhancements
  client/package-lock.json
  client/package.json
  client/src/Routes.tsx
  client/src/common/AuditLogRow.tsx
  client/src/common/RequestWrapper2.tsx
  client/src/common/SearchBar.tsx
  client/src/left_nav/LeftNav.tsx
  client/src/pages/admin/audit_logs/AuditLogEntity.tsx
  client/src/pages/admin/audit_logs/AuditLogRow.tsx
  client/src/pages/admin/audit_logs/AuditLogsPage.tsx
  client/src/pages/admin/users/UserModal.tsx
  client/src/pages/admin/users/UsersPage.tsx
  client/src/test_data/Logs.ts
  server/src/auth.ts
  server/src/db/migrations/20220317233259_audit-logs-enhancements.ts
  server/src/mappers/auditLogs/auditLogMapper.ts
  server/src/models/auditLogs/auditLogs.ts
  server/src/models/auditLogs/auditLogsInput.ts
  server/src/models/auditLogs/eventTypes.ts
  server/src/repositories/AuditLogs/AuditLogRepository.ts
  server/src/repositories/Equipment/EquipmentRepository.ts
  server/src/repositories/Rooms/RoomRepository.ts
  server/src/repositories/Users/UserRepository.ts
  server/src/resolvers/auditLogsResolver.ts
  server/src/resolvers/equipmentResolver.ts
  server/src/resolvers/roomsResolver.ts
  server/src/resolvers/storeFrontResolver.ts
  server/src/resolvers/trainingResolver.ts
  server/src/resolvers/usersResolver.ts
  server/src/schema.ts
  server/src/schemas/auditLogsSchema.ts
  server/src/schemas/roomsSchema.ts
  server/src/schemas/usersSchema.ts
  server/src/server.ts
Labels: enhancement, backend, frontend

#176 Room monitoring enhancements
  client/src/Routes.tsx
  client/src/left_nav/CardReaderAlert.tsx
  client/src/left_nav/LeftNav.tsx
  client/src/left_nav/NavLink.tsx
  client/src/pages/admin/audit_logs/AuditLogEntity.tsx
  client/src/pages/admin/monitor/CardReader.tsx
  client/src/pages/admin/monitor/EquipmentQualificationsCard.tsx
  client/src/pages/admin/monitor/MonitorRoomPage.tsx
  client/src/pages/admin/monitor/RoomCard.tsx
  client/src/pages/admin/monitor/SelectRoomPage.tsx
  client/src/pages/admin/monitor/SwipedUserCard.tsx
  client/src/pages/maker/signup/SignupPage.tsx
  server/src/db/migrations/20220320213244_room-swipes.ts
  server/src/repositories/AuditLogs/AuditLogRepository.ts
  server/src/repositories/Equipment/EquipmentRepository.ts
  server/src/repositories/Rooms/RoomRepository.ts
  server/src/repositories/Users/UserRepository.ts
  server/src/resolvers/equipmentResolver.ts
  server/src/resolvers/roomsResolver.ts
  server/src/resolvers/usersResolver.ts
  server/src/schemas/roomsSchema.ts
  server/src/schemas/usersSchema.ts
Labels: enhancement, backend, frontend

#179 Archiving Equip instead of Deleting
  server/src/db/migrations/20220322194711_equipment-archive.ts
  server/src/mappers/equipment/Equipment.ts
  server/src/mappers/equipment/Reservation.ts
  server/src/models/equipment/equipment.ts
  server/src/models/equipment/reservation.ts
  server/src/repositories/Equipment/EquipmentRepository.ts
  server/src/repositories/Equipment/ReservationRepository.ts
  server/src/resolvers/equipmentResolver.ts
  server/src/schemas/equipmentSchema.ts
Labels: refactoring, backend

#182 Lots of frontend chores
  .github/workflows/frontend.yml
  client/README.md
  client/config-overrides.js
  client/package-lock.json
  client/package.json
  client/public/apple-touch-icon.png
  client/public/favicon.ico
  client/public/index.html
  client/src/App.tsx
  client/src/AppRoutes.tsx
  client/src/Routes.tsx
  client/src/common/CurrentUserProvider.tsx
  client/src/index.tsx
  client/src/left_nav/LeftNav.tsx
  client/src/pages/admin/audit_logs/AuditLogEntity.tsx
  client/src/pages/admin/audit_logs/AuditLogsPage.tsx
  client/src/pages/admin/edit_module/EditModulePage.tsx
  client/src/pages/admin/inventory/InventoryPage.tsx
  client/src/pages/admin/manage_equipment/DeleteEquipmentButton.tsx
  client/src/pages/admin/manage_equipment/ManageEquipmentPage.tsx
  client/src/pages/admin/monitor/MonitorRoomPage.tsx
  client/src/pages/admin/monitor/RoomCard.tsx
  client/src/pages/admin/monitor/SwipedUserCard.tsx
  client/src/pages/admin/training_modules/TrainingModule.tsx
  client/src/pages/admin/training_modules/TrainingModulesPage.tsx
  client/src/pages/admin/users/UserModal.tsx
  client/src/pages/admin/users/UsersPage.tsx
  client/src/pages/both/equipment/EquipmentCard.tsx
  client/src/pages/both/equipment/EquipmentPage.tsx
  client/src/pages/maker/create_reservation/ConfirmationStep.tsx
  client/src/pages/maker/signup/SignupPage.tsx
  client/src/queries/getUsers.ts
  client/src/reportWebVitals.ts
  client/src/setupTests.ts
  client/src/test/LeftNav.test.tsx
  client/src/test/SSO.test.tsx
  client/src/test/SignupPage.test.tsx
  client/src/test/TestUtils.tsx
  client/src/test_data/AdamSavage.ts
  client/src/test_data/CollectiveExpertAvailability.json
  client/src/test_data/Users.ts
  client/src/types/Log.ts
  client/tsconfig.json
Labels: refactoring, frontend, tests

#183 Bismillah module submissions
  server/src/db/migrations/20211102194503_machines_table.ts
  server/src/db/migrations/20220324210801_module_submissions_table.ts
Labels: backend

#188 Better auth function
  server/src/context.ts
  server/src/repositories/Rooms/RoomRepository.ts
  server/src/resolvers/auditLogsResolver.ts
  server/src/resolvers/roomsResolver.ts
  server/src/resolvers/usersResolver.ts
  server/src/server.ts
Labels: refactoring, backend

#192 Archiving Training Modules
  server/src/db/migrations/20220327205516_training-modules-archive.ts
  server/src/repositories/Equipment/ReservationRepository.ts
  server/src/repositories/Training/ModuleItemRepository.ts
  server/src/repositories/Training/ModuleRepository.ts
  server/src/repositories/Training/OptionRepository.ts
  server/src/resolvers/trainingResolver.ts
Labels: refactoring, backend

#190 Signup & module browser tests
  client/package.json
  client/src/pages/admin/training_modules/TrainingModulesPage.tsx
  client/src/test/SignupPage.test.tsx
  client/src/test/TestUtils.tsx
  client/src/test/admin/ModuleBrowser.test.tsx
  server/src/repositories/Training/ModuleRepository.ts
Labels: frontend, tests

#187 Remove labbie room monitoring
  server/src/db/migrations/20220325155145_remove-monitoring.ts
  server/src/repositories/Rooms/RoomRepository.ts
  server/src/resolvers/roomsResolver.ts
  server/src/schemas/roomsSchema.ts
Labels: refactoring, backend

#189 Holds schema + interfaces
  server/src/schemas/holdsSchema.ts
  server/src/schemas/usersSchema.ts
Labels: enhancement, backend

#198 Holds implementation
  client/src/common/CurrentUserProvider.tsx
  client/src/common/PrettyModal.tsx
  client/src/left_nav/HoldAlert.tsx
  client/src/left_nav/LeftNav.tsx
  client/src/pages/admin/users/HoldCard.tsx
  client/src/pages/admin/users/UserModal.tsx
  client/src/test/LeftNav.test.tsx
  client/src/test/TestUtils.tsx
  server/src/EntityNotFound.ts
  server/src/auth.ts
  server/src/context.ts
  server/src/db/migrations/20220126063347_holds_table.ts
  server/src/repositories/Holds/HoldsRepository.ts
  server/src/repositories/Users/UserRepository.ts
  server/src/resolvers/holdsResolver.ts
  server/src/resolvers/usersResolver.ts
  server/src/schema.ts
  server/src/schemas/holdsSchema.ts
  server/src/schemas/usersSchema.ts
Labels: enhancement, backend, frontend
