Repository rit-construct-makerspace/makerspace, pull requests merged in 2022-02, with the labels that each got.

#72 Create purchase order UI prototype
  client/src/Routes.tsx
  client/src/common/CloseButton.tsx
  client/src/pages/admin/create_purchase_order/CreatePurchaseOrderPage.tsx
  client/src/pages/admin/create_purchase_order/Criterion.tsx
  client/src/pages/admin/create_purchase_order/PurchaseOrderExplainer.tsx
  client/src/pages/admin/inventory/PurchaseOrderList.tsx
Labels: enhancement, frontend

#61 Create holds schema
  server/src/schemas/holdsSchema.ts
  server/src/schemas/machinesSchema.ts
Labels: backend

#59 Create holds migration
  server/src/db/migrations/20210923214317_initial_users.ts
  server/src/db/migrations/20211102194503_machines_table.ts
  server/src/db/migrations/20220126063347_holds_table.ts
Labels: backend

#85 update README to be more noob friendly (like me)
  server/README.md
Labels: documentation, backend

#87 Refactoring of machines schema and table + datetime resolver + fixes
  server/src/db/migrations/20211102194503_machines_table.ts
  server/src/schemas/holdsSchema.ts
  server/src/schemas/machinesSchema.ts
  server/src/schemas/usersSchema.ts
Labels: refactoring, backend

#93 Create inventory items from the frontend
  client/package.json
  client/src/pages/Page.tsx
  client/src/pages/admin/edit_material/EditMaterialPage.tsx
  client/src/pages/admin/inventory/InventoryPage.tsx
Labels: enhancement, frontend

#98 Query for inventory items from the frontend
  client/src/common/InventoryRow.tsx
  client/src/common/RequestWrapper.tsx
  client/src/pages/admin/inventory/InventoryPage.tsx
  client/src/pages/admin/inventory/RunningLow.tsx
  client/src/pages/admin/manage_user/DangerZone.tsx
  server/package-lock.json
Labels: enhancement, frontend

#118 Update materials from the frontend
  client/src/Routes.tsx
  client/src/common/RequestWrapper.tsx
  client/src/pages/admin/edit_material/DeleteMaterialButton.tsx
  client/src/pages/admin/edit_material/EditMaterialPage.tsx
  client/src/pages/admin/edit_material/MaterialEditor.tsx
  client/src/pages/admin/edit_material/MaterialPage.tsx
  client/src/pages/admin/edit_material/NewMaterialPage.tsx
  client/src/pages/admin/inventory/InventoryPage.tsx
Labels: enhancement, frontend

#99 repo, mappers and resolvers for equipment backend
  server/src/mappers/equipment/Equipment.ts
  server/src/mappers/equipment/EquipmentLabel.ts
  server/src/mappers/equipment/Reservation.ts
  server/src/mappers/training/TrainingModuleMapper.ts
  server/src/models/equipment/equipment.ts
  server/src/models/equipment/equipmentInput.ts
  server/src/models/equipment/equipmentLabel.ts
  server/src/models/equipment/equipmentLabelInput.ts
  server/src/models/equipment/reservation.ts
  server/src/models/equipment/reservationInput.ts
  server/src/models/training/trainingModule.ts
  server/src/repositories/Equipment/EquipmentLabelRepository.ts
  server/src/repositories/Equipment/EquipmentRepository.ts
  server/src/repositories/Equipment/ReservationRepository.ts
  server/src/resolvers/equipmentResolver.ts
Labels: enhancement, backend

#124 Added inventory queries to other pages
  client/src/App.tsx
  client/src/common/InventoryRow.tsx
  client/src/common/PreviewInventoryRow.tsx
  client/src/pages/admin/inventory/InventoryPage.tsx
  client/src/pages/admin/storefront/StorefrontPage.tsx
  client/src/pages/maker/inventory_preview/InventoryPreviewPage.tsx
Labels: enhancement, frontend

#125 Initial reservations schema
  server/package-lock.json
  server/src/schema.ts
  server/src/schemas/machinesSchema.ts
  server/src/schemas/reservationsSchema.ts
Labels: enhancement, backend

#126 Thanos snap purchase orders
  client/src/Routes.tsx
  client/src/pages/admin/create_purchase_order/CreatePurchaseOrderPage.tsx
  client/src/pages/admin/create_purchase_order/Criterion.tsx
  client/src/pages/admin/create_purchase_order/PurchaseOrderExplainer.tsx
  client/src/pages/admin/inventory/PurchaseOrder.tsx
  client/src/pages/admin/inventory/PurchaseOrderItemRow.tsx
  client/src/pages/admin/inventory/PurchaseOrderList.tsx
  client/src/test_data/PurchaseOrders.tsx
  client/src/types/PurchaseOrder.ts
  server/src/mappers/store/PurchaseOrderItemMapper.ts
  server/src/mappers/store/PurchaseOrderMapper.ts
  server/src/models/auditLogs/eventTypes.ts
  server/src/models/store/purchaseOrder.ts
  server/src/models/store/purchaseOrderInput.ts
  server/src/models/store/purchaseOrderItem.ts
  server/src/models/store/purchaseOrderItemInput.ts
  server/src/repositories/Store/purchaseOrderRepository.ts
  server/src/resolvers/storeFrontResolver.ts
  server/src/schemas/auditLogsSchema.ts
  server/src/schemas/storeFrontSchema.ts
Labels: refactoring, backend, frontend

#131 Frontend inventory enhancements
  client/src/Routes.tsx
  client/src/common/RequestWrapper.tsx
  client/src/pages/admin/edit_material/MaterialPage.tsx
  client/src/pages/admin/inventory/DeleteMaterialButton.tsx
  client/src/pages/admin/inventory/EditMaterial.tsx
  client/src/pages/admin/inventory/InventoryPage.tsx
  client/src/pages/admin/inventory/MaterialModal.tsx
  client/src/pages/admin/inventory/MaterialModalContents.tsx
  client/src/pages/admin/inventory/NewMaterial.tsx
  client/src/pages/admin/inventory/RunningLow.tsx
  client/src/pages/admin/storefront/StorefrontPage.tsx
  client/src/pages/maker/inventory_preview/InventoryPreviewPage.tsx
  client/src/queries/getInventoryItems.ts
  client/src/test_data/Inventory.ts
  client/src/test_data/ItemCategories.tsx
  client/src/types/InventoryItem.ts
Labels: enhancement, frontend

#136 Innalillah labels
  server/src/db/migrations/20211102194503_machines_table.ts
  server/src/mappers/equipment/EquipmentLabel.ts
  server/src/models/equipment/equipmentInput.ts
  server/src/models/equipment/equipmentLabel.ts
  server/src/models/equipment/equipmentLabelInput.ts
  server/src/repositories/Equipment/EquipmentLabelRepository.ts
  server/src/repositories/Equipment/EquipmentRepository.ts
  server/src/resolvers/equipmentResolver.ts
  server/src/schemas/equipmentSchema.ts
  server/src/schemas/machinesSchema.ts
Labels: enhancement, backend
